[package]
name = "cli"
version = "0.1.0"
authors = ["amy null <null@amy.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsquish = { path = "../libsquish" }

clap = "3.0.0-beta.2"
hyper = { version = "0.14.13", features = [ "stream" ] }
hyperlocal = "0.8.0"
serde = "1.0.126"
serde_json = "1.0.68"
tokio = { version = "1.6.1", features = [ "full" ] }
