[package]
name = "cli"
version = "0.1.0"
authors = ["amy null <null@amy.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.9", features = [ "stream" ] }
hyperlocal = "0.8.0"
reqwest = "0.11.3"
tokio = { version = "1.6.1", features = [ "full" ] }
