[package]
name = "daemon"
version = "0.1.0"
authors = ["amy null <null@amy.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsquish = { path = "../libsquish" }

flate2 = "1.0.20"
haikunator = "0.1.2"
hex = "0.4.3"
hmac-sha256 = "0.1.7"
log = "0.4.14"
nix = "0.21.0"
pretty_env_logger = "0.4.0"
rlimit = "0.5.4"
reqwest = "0.11.3"
tar = "0.4.35"
tokio = { version = "1.6.1", features = [ "full" ] }
tokio-stream = { version = "0.1.6", features = [ "net" ] }
tokio-util = { version = "0.6", features = ["io"] }
warp = "0.3.1"
yaml-rust = "0.4.5"
