[package]
name = "pid1"
version = "0.1.0"
authors = ["amy null <null@amy.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = "3.0.0-beta.2"
futures = "0.3.15"
nix = "0.21.0"
rand = "0.8.3"
reqwest = "0.11.3"
rlimit = "0.5.4"
rtnetlink = "0.7.0"
tokio = { version = "1.6.1", features = [ "full" ] }
