[package]
name = "pid1"
version = "0.1.0"
authors = ["amy null <null@amy.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsquish = { path = "../libsquish" }

clap = "3.0.0-beta.4"
futures = "0.3.17"
nix = "0.23.0"
reqwest = "0.11.4"
rlimit = "0.6.2"
tokio = { version = "1.12.0", features = [ "full" ] }
