#!/usr/bin/env bash

# Pre-commit hook
rm ./.git/hooks/pre-commit > /dev/null
echo 'echo ">> Running \`cargo fmt\`..."' >> ./.git/hooks/pre-commit
echo 'cargo fmt' >> ./.git/hooks/pre-commit
echo 'echo ">> Done!"' >> ./.git/hooks/pre-commit
chmod +x ./.git/hooks/pre-commit
