#!/usr/bin/env bash

# Pre-commit hook
HOOK="./.git/hooks/pre-commit"
rm $HOOK > /dev/null
echo 'echo ">> Running \`cargo fmt\`..."' >> $HOOK
echo 'git add $(cargo fmt --message-format short)' >> $HOOK
echo 'echo ">> Done!"' >> $HOOK
chmod +x $HOOK
