name: Run clippy lints
on:
  push:
    branches:
      - mistress
  pull_request:
    branches:
      - mistress

jobs:
  run-tests:
    if: github.actor != 'dependabot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: Swatinem/rust-cache@v1
      - name: Run clippy
        run: cargo clippy
